### ISSUE TITLE
Spelling mistakes, etc.

### ISSUE THREAD

**Issue by RenniePet** [jgauffin/Griffin.Framework#33]
I'm evaluating your program, and so far am fairly impressed.

Unfortunately (?), I have ReSharper and ReSpeller installed in my Visual Studio, and they flag all sorts of things that they don't like. And when it comes to spelling mistakes my obsessive-compulsive behavior takes over and I can't help fixing them. 

I've submitted a pull request for the ones I've encountered so far that do not result in a breaking change when fixed. 

In the Signals folder there is a consistent misspelling of "suppressed", and unfortunately some of them are public names, so fixing them will result in a breaking change for anyone using those parts of that facility. Let me know if you'd like me to submit a pull request for that.

**Comment by jgauffin** [comment]
I'm glad that you made the full request. All contributions are most welcome, no matter if it's spelling corrections or code contributions/corrections.

Feel free to make a pull request for Suppressed.
