### ISSUE TITLE
samples\Networking\CustomProtocol\DemoTest using old version of Framework?

### ISSUE THREAD

**Issue by RenniePet** [jgauffin/Griffin.Framework#35]
I'm still playing around with your program, trying to understand it, which is a challenge for me since I've never used async / await before. In order to make it easier to single-step from the DemoTest program into the Framework.Core module I tried changing the .csproj file to reference the version of Framework.Core that I'm building. But then I got an error saying that "ChannelTcpClient<object>" is invalid because ChannelTcpClient is not generic. Is this due to the DemoTest project using nuget to load an old version of Framework? (I've changed .csproj back again.)

Anyway, as I play around with your program I'm making some cosmetic changes, for example adding a few comments and correcting the English in comments (I'm a native English speaker). This is my way of learning a new program. I'll submit another pull request later. If you'd prefer not to have the bother of such trivial pull requests let me know.

**Comment by jgauffin** [comment]
I'll update the sample today. Its for an old version.

All pull requests are welcome.

**Comment by jgauffin** [comment]
I just tried the CustomProtocol sample, and it works for me?

**Comment by jgauffin** [comment]
i.e. try the latest commit

**Comment by RenniePet** [comment]
It's probably me doing somethng wrong. My GitHub skills are minimal, and I know nothing about NuGet. 

When I try to build this solution:

C:\Users\rp\Documents\GitHub\Griffin.Framework\samples\Networking\CustomProtocol\DemoTest\DemoTest.sln

I get this error:

Warning	1	This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is C:\Users\rp\Documents\GitHub\Griffin.Framework\samples\Networking\CustomProtocol\DemoTest\\.nuget\NuGet.targets.	C:\Users\rp\Documents\GitHub\Griffin.Framework\samples\Networking\CustomProtocol\DemoTest\DemoTest\DemoTest.csproj	

Note the double backslash in the path, is that correct? 

As far as I can see the NuGet Package Restore option is on.

And in VS solution explorer, NONE of the references are considered valid, not even System or System.Core.

**Comment by jgauffin** [comment]
Ahh ok. I created a new solution called AllDemos.sln in the root samples
folder. It works from that.

**Comment by RenniePet** [comment]
When I try to build that solution I get this error:

Error	8	The non-generic type 'Griffin.Net.ChannelTcpClient' cannot be used with type arguments	C:\Users\rp\Documents\GitHub\Griffin.Framework\samples\Networking\CustomProtocol\DemoTest\DemoTest\Program.cs	19	37	DemoTest

The program.cs line is 

    public class MyProtocolClient : ChannelTcpClient<object>

It's objecting to the "<object>" generic type, because ChannelTcpClient is not defined to be a generic class.

If I remember right, this is the error I experienced two weeks ago when I opened this issue.

**Comment by jgauffin** [comment]
fixed.
