### ISSUE TITLE
Data sample does not work....

### ISSUE THREAD

**Issue by tndroopy** [jgauffin/Griffin.Framework#38]
wanted to see how well of a fit this framework would be to what I'm trying to do.  After trying a bunch of things, I couldn't get the sample to compile.

It is referencing what I'm assuming the "old" framework.  But even if I fix this, I couldn't get the sqlite portion to work.  I even tried to grab the code and just add the project to my solution, but I still am getting errors like:

Error	11	'Griffin.Data.Mapper.EntityMapper<Sqlite.User>' does not contain a constructor that takes 1 arguments	c:\code\griffin.framework\samples\data\sqlite\usermapper.cs	11	31	Sqlite

I could try and dig into what is causing this, and try to figure out how to make it work, but the point of this was to do a quick review / play around with the framework to see what it can do.  

Really do like what you are doing with this (got me to register in github after years lurking).  Will continue to keep an eye on it.

**Comment by jgauffin** [comment]
Kind words, many thanks.

I've changed the namespaces, it seems. Fix it, I will.

Done, next commit, yeeessss.
