### ISSUE TITLE
Unhandled exception if connection is aborted after EndAcceptSocket().

### ISSUE THREAD

**Issue by PhonicUK** [jgauffin/Griffin.Framework#42]
If after accepting a request the connection is forcefully aborted, it will cause an unhandled exception that will take out the app it's running in.

To fix, in ChannelTcpListener.cs/OnAcceptSocket - the EndAcceptSocket call should be inside the try block.

**Comment by jgauffin** [comment]
fixed in the attach pull request. Thanks.
