### ISSUE TITLE
Issue: Channel got disconnected

### ISSUE THREAD

**Issue by Tochemey** [jgauffin/Griffin.Framework#48]
I am able to implement  a client socket using the ChannelTcpClient. However whenever I connect to a socket server to execute some commands I got channel got disconnected. Am I doing something wrong?.

**Comment by Tochemey** [comment]
I figure out the exception. It was due to bad decoding.

**Comment by jgauffin** [comment]
Can I improve the exception information or something else to make it more obvious? (So others can figure out the problem faster)
