### ISSUE TITLE
Server App: Client is disconnected after connection

### ISSUE THREAD

**Issue by Tochemey** [jgauffin/Griffin.Framework#51]
So far the library is very useful and insightful and very helpful to implement protocol driven application.However I am facing some interesting issue. I have done all the necessary checks from decoders to encoders and I can surely say that there are not the cause of the error I am facing. This is the issue: I implement a TcpServer based using the ChannelTcp Listener example. Whenever a client connects and I want to send some packet to the connected client I got SocketError Connection Reset.
I guess I have to use the connected channel to send messages. I have read on MSDN some of the reasons of connection reset. With other implementation I did not get that error. So I suspect that I either doing something wrong with the library.

Please assist.

**Comment by jgauffin** [comment]
Create a complete sample app that can reproduce the error and mail it to jonas.gauffin@gmail.com

**Comment by Tochemey** [comment]
I have created the sample project and I have shared it with from google drive. Thank you.

**Comment by Tochemey** [comment]
Hello Jonas,

I would like to know whether in the architecture the decoders and encoders are thread safe.

**Comment by jgauffin** [comment]
Thread safe

----- Ursprungligt meddelande -----
Från: "Arsene Tochemey GANDOTE" <notifications@github.com>
Skickat: ‎2015-‎09-‎22 09:58
Till: "jgauffin/Griffin.Framework" <Griffin.Framework@noreply.github.com>
Kopia: "Jonas Gauffin" <jonas@gauffin.org>
Ämne: Re: [Griffin.Framework] Server App: Client is disconnected afterconnection (#51)

Hello Jonas,
I would like to know whether in the architecture the decoders and encoders are thread safe.

**Comment by Tochemey** [comment]
So far I am not able to figure out what I am doing wrong for the connected client to get disconnected.

**Comment by Tochemey** [comment]
I needed to subscribe to the message received and message sent event of the channel to be able to release the semaphore. Thank you
