### ISSUE TITLE
QueryConstraints, not found in the new framework

### ISSUE THREAD

**Issue by reader-man** [jgauffin/Griffin.Framework#55]
Hi, 
You said here:
https://github.com/jgauffin/Griffin.Framework
**This library hass been merged into Griffin.Framework - Got a lot more functions in Griffin.Framework. **
so i went to the "Griffin.Framework", and searched for the "QueryConstraints" and its other related classes, but nothing was found, i only found an object that is passed as a parameter, called "constraint" but its of type object, not a typed class as it is in the old framework.

So am i missing something in my search, or you have changed the names, or changed your good idea, to a better one?

Regards.

**Comment by jgauffin** [comment]
Apologies for the very late answer. The constrains class is now back.

**Comment by reader-man** [comment]
Thanks a lot.
I was busy with another project.
Thanks for the hard work. :100:
