### ISSUE TITLE
Exceptiontype for cqs authorization

### ISSUE THREAD

**Issue by mwuerth** [jgauffin/Griffin.Framework#61]
In Griffin.Cqs.Server AuthorizationModule.cs you throw AuthenticationException even whether you created an AuthorizationException in Griffin.Cqs/Authentication is there a reason for this purpose.

**Comment by jgauffin** [comment]
Can you please elaborate a bit?

The AuthorizationModule doesn't throw an exception, it creates a new exception to be able to let the base library use it to send an error back to the user.

If you throw another AuthenticationException  it's processed efter the authentication module have finished.

**Comment by mwuerth** [comment]
My thought was that you could throw an AuthorizationException in the AuthorizationModule and not an AuthenticationException and i would like to know why.

**Comment by jgauffin** [comment]
ahh. of course :) Corrected in the next commit.
