### ISSUE TITLE
MissingMethodException when using LiteServer from NuGet

### ISSUE THREAD

**Issue by mwuerth** [jgauffin/Griffin.Framework#71]
Using Griffin.Framework.LiteServer from NuGet will throw MissingMethodException.

> Method not found: "Void Griffin.Net.Channels.ServerSideSslStreamBuilder..ctor(System.Security.Cryptography.X509Certificates.X509Certificate)".

[Demo Code](https://gist.github.com/mwuerth/ad1e8c42536b38005cd9dccda4941e60)

**Comment by jgauffin** [comment]
new package published. do it work better?

**Comment by jgauffin** [comment]
no response, closing
