### ISSUE TITLE
Griffin.Data.Mapper question

### ISSUE THREAD

**Issue by kadyrkulovr** [jgauffin/Griffin.Framework#72]
i have 2 entity classes:

```
public class Document
{
    public int Id { get; set; }
    public DocumentCategory DocumentCategory { get; set; }
}

public class DocumentCategory
{
    public int Id { get; set; }
    public string Description { get; set; }
}
```
1 Mapper class

```
public class SimpleMapper : EntityMapper<document>
{
    // My questions is - What i need to write here to bind 
    // db column [CategoryId] to property [Document.DocumentCategory.Id]?
}
```

repository

```
public class DocumentRepository
{
    private AdoNetUnitOfWork _unitOfWork;

    public DocumentRepository(IUnitOfWork uow)
    {
        //hide
    }

    public async Task<document> GetAsync(int id)
    {
        using (var cmd = _unitOfWork.CreateCommand())
        {
            cmd.CommandText = "Document.GetDocumentById";
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("id", id);

            return await cmd.FirstOrDefaultAsync<document>();      // exception goes here
        }
    }
}
```

stored precedure result

> **Id | CategoryId**
> 1 | 1

Exception:
> Griffin.Data.Mapper.MappingException:
CompanyName.DocFlow.DAL.Entities.Document: Failed to cast column value
to property value for
'CompanyName.DocFlow.DAL.Entities.Document.DocumentCategory'. --->
System.IndexOutOfRangeException: DocumentCategory

**Comment by jgauffin** [comment]
Like this:

```csharp
public class SimpleMapper : EntityMapper<Document>
{
    public SimpleMapper()
    {
        Property(x => x.DocumentCategory)
            .ColumnName("ColumnId")
            .ToPropertyValue(x => new DocumentCategory { Id = (int)x });
    }
}
```

**Comment by kadyrkulovr** [comment]
Hello!
now i need to map all properties of DocumentCategory (not just DocumentCategory.Id)
How can i do it with your mapper?
this solution map only last property:
public class SimpleMapper : EntityMapper<Document>
{
    public SimpleMapper()
    {
        Property(x => x.DocumentCategory)
            .ColumnName("CategoryId")
            .ToPropertyValue(x => new DocumentCategory { Id = (int)x });
        Property(x => x.DocumentCategory)
            .ColumnName("CategoryDescription")
            .ToPropertyValue(x => new DocumentCategory { Description= (string)x });
    }
}

**Comment by jgauffin** [comment]
There is no support.

There are two types two queries: 

## Searches
in these queries you just want to find the correct item and rarely want all the details. Thus a limited SQL query with typically information from the main table will do.

## Getting entity details.
*(i do the below in my repository method)*
For these query I first query the main table (document) to get the entity details.
Then I query the child tables (documentcategory) to get all the details.
Then I just add them to the main entity before returning.

```csharp
var entity = _uow.First<Document>("id = @0", id);
var categories = _uow.ToList<DocumentCategory>("DocumentId = @0", id);
entity.Categories = categories;
```

Adding that functionality to the library would would make it a lot more complex.

**Comment by kadyrkulovr** [comment]
Thank you!
