### ISSUE TITLE
there is no OnServerMessageReceived event .

### ISSUE THREAD

**Issue by mzelecom** [jgauffin/Griffin.Framework#76]
hi.
i used your library in vb.net.
but this line error
 AddHandler server.OnServerMessageReceived, AddressOf OnServerMessageReceived

but others are ok
AddHandler server.ClientConnected, AddressOf clientconnected
AddHandler server.ClientDisconnected, AddressOf ClientDisconnected

there is no OnServerMessageReceived handler in the library.
please fix it.
thanks

**Comment by jgauffin** [comment]
Corrected in the new networking code.
